In [27]:
import csv
import numpy as np
import pandas as pd

In [28]:
#Choix de la distance :(lÃ  c'est edition)


Choix_distance = "matrice"
Choix_distance = "edition"

In [29]:
csvFile = open("reponse.csv", "r")
reader = csv.reader(csvFile)
list_participant = []
for item in reader:
    if item[0] not in list_participant: 
        list_participant.append(item[0])
csvFile.close()

csvFile = open("reponse.csv", "r")
reader = csv.reader(csvFile)
list1 = []
list2 = []
list3 = []
list4 = []
for item in reader:
    list1.append(item[0])
    list2.append(item[1])
    list3.append(item[3])
    list4.append(item[4])
csvFile.close()
data = {'repas': list2, 'temps': list3, 'notes': list4}
df_reponse = pd.DataFrame(data, index = list1)

In [30]:
csvFile = open("repas.csv", "r")
reader = csv.reader(csvFile)
list1 = []
list2 = []
list3 = []
list4 = []
list5 = []
for item in reader:
    list1.append(item[0])
    list2.append(item[1])
    list3.append(item[4])
    list4.append(item[5])
    list5.append(item[6])
csvFile.close()
data = {'repas':list1, 'id': list2, 'accompagnment': list3, 'protein': list4, 'dessert': list5}
df_repas = pd.DataFrame(data)

In [31]:
#distances
def ddm(series1, series2): 
    if Choix_distance == "edition":
        distance1 = 0
        distance2 = 0
        for i in range(4,7): 
            distance1 += abs(int(series1[i]) - int(series2[i]))
        for i in range(11,14):
            distance2 += (abs(int(series1[i]) - int(series2[i])) >= 1)*1
    else :
        
        p = np.array([
            [0, 0, 1, 2, 3, 4, 5, 6, 7, 7], 
            [0, 0, 0, 2, 3, 4, 5, 6, 7, 7], 
            [1, 0, 0, 4, 6, 2, 7, 3, 5, 5], 
            [2, 2, 4, 0, 5, 1, 3, 7, 6, 6], 
            [3, 3, 6, 5, 0, 7, 2, 1, 4, 4], 
            [4, 4, 2, 1, 7, 0, 6, 5, 3, 3], 
            [5, 5, 7, 3, 2, 6, 0, 4, 1, 1], 
            [6, 6, 3, 7, 1, 5, 4, 0, 2, 2], 
            [7, 7, 5, 6, 4, 3, 1, 2, 0, 0], 
            [7, 7, 5, 6, 4, 3, 1, 2, 0, 0]
        ])
        v = np.array([
            [0, 7, 7, 5, 6, 4, 4, 1, 7, 6], 
            [7, 0, 4, 1, 2, 6, 7, 5, 2, 4], 
            [7, 4, 0, 4, 4, 5, 3, 7, 1, 2], 
            [5, 1, 4, 0, 4, 6, 7, 7, 4, 4], 
            [6, 2, 4, 4, 0, 7, 7, 3, 2, 1], 
            [4, 6, 5, 6, 7, 0, 2, 4, 7, 5], 
            [4, 7, 3, 7, 7, 2, 0, 4, 6, 5], 
            [1, 5, 7, 7, 3, 4, 4, 0, 5, 6], 
            [7, 2, 1, 4, 2, 7, 6, 5, 0, 4], 
            [6, 4, 2, 4, 1, 5, 5, 6, 4, 0]
        ])
        p=np.where(p==1, 20, p)
        p=np.where(p==3, 1, p)
        p=np.where(p==2, 3, p)
        p=np.where(p==20, 2, p)
        p=np.where(p==4, 60, p)
        p=np.where(p==6, 4, p)
        p=np.where(p==60, 6, p)
        v=np.where(v==1, 20, v)
        v=np.where(v==3, 1, v)
        v=np.where(v==2, 3, v)
        v=np.where(v==20, 2, v)
        v=np.where(v==4, 60, v)
        v=np.where(v==6, 4, v)
        v=np.where(v==60, 6, v)
        distance1 = p[int(series1[3])-1][int(series2[3])-1]
        distance2 = v[int(series1[10])-1][int(series2[10])-1]
        
    return distance1, distance2

#pour les notes:

def distance_note(ligne1, ligne2):
    
    prem = int(ligne1[2])
    sec = int(ligne2[2])
    var1 = (prem != sec)*(-1)**(prem>sec)

    prem = int(ligne1[9])
    sec = int(ligne2[9])
    var2 = (prem != sec)*(-1)**(prem>sec)
    return var1, var2

In [32]:
Ap = []; MSp = []; SMp = []; MMp = []; SSp = []
Av = []; MSv = []; SMv = []; MMv = []; SSv = []
Nv = []; Np = []; Nmmp = []; Nssp = []; Nmmv = []; Nssv = []

In [33]:
for i in range(0, len(list_participant)-1): 
    name = list_participant[i]
    df_participant = df_reponse[df_reponse.index == list_participant[i]]
    df_participant1 = pd.merge(df_participant, df_repas, on = 'repas')
    df_participant1.index = df_participant.index
    df_participant2 = pd.concat([df_participant1[0:10].sort_values(by = "temps"), 
                                 df_participant1[10:20].sort_values(by = "temps")], 
                                 axis = 1)
    df_participant2.columns = ['repas_p', 'temps_p', 'notes_p', 
                               'i_p', 'a_p', 'p_p', 'd_p', 
                               'repas_v', 'temps_v', 'notes_v', 
                               'i_v', 'a_v', 'p_v', 'd_v']
    df_participant3 = pd.DataFrame([
        df_participant2.iloc[0], 
        df_participant2.iloc[2], 
        df_participant2.iloc[4], 
        df_participant2.iloc[6], 
        df_participant2.iloc[8]
    ])
    df_participant4 = pd.DataFrame([
        df_participant2.iloc[1], 
        df_participant2.iloc[3], 
        df_participant2.iloc[5], 
        df_participant2.iloc[7], 
        df_participant2.iloc[9]
    ])
    df_participant5 = pd.concat([df_participant2, df_participant3, df_participant4])
    list1 = []
    list2 = []
    
    note_p = []
    note_v = []
    for i in range(0,20):
        if i < 19:
            list1.append(ddm(df_participant5.iloc[i], df_participant5.iloc[i+1])[0])
            list2.append(ddm(df_participant5.iloc[i], df_participant5.iloc[i+1])[1])
            
            #recuperation des notes
            note_p.append(distance_note(df_participant5.iloc[i], df_participant5.iloc[i+1])[0])
            note_v.append(distance_note(df_participant5.iloc[i], df_participant5.iloc[i+1])[1])

            
        else: 
            list1.append(ddm(df_participant5.iloc[i], df_participant5.iloc[0])[0])
            list2.append(ddm(df_participant5.iloc[i], df_participant5.iloc[0])[1])
            note_p.append(distance_note(df_participant5.iloc[i], df_participant5.iloc[0])[0])
            note_v.append(distance_note(df_participant5.iloc[i], df_participant5.iloc[0])[1])
            
            
    df_participant5['score_p'] = list1
    df_participant5['score_v'] = list2
    
    df_participant5['var_note_p'] = note_p
    df_participant5['var_note_v'] = note_v

    test = df_participant5.ix[:,[3,2,14,10,9,15,16,17]]
    
    ap = []; msp = []; smp = []; mmp = []; ssp = []
    av = []; msv = []; smv = []; mmv = []; ssv = []
    np = []; nv = []; nmmp = []; nssp = []; nmmv = []; nssv = []
    
    for i in range(0, 19): 
        if i < 9: 
            ap.append(test.iloc[i][2])
            av.append(test.iloc[i][5])
            np.append(test.iloc[i][6]) 
            nv.append(test.iloc[i][7])    

            if i%2 == 0: 
                msp.append(test.iloc[i][2])
                msv.append(test.iloc[i][5])
            else: 
                smp.append(test.iloc[i][2])
                smv.append(test.iloc[i][5])
        elif i ==9: 
            i += 1
        elif i < 14: 
            mmp.append(test.iloc[i][2])
            mmv.append(test.iloc[i][5])
            nmmp.append(test.iloc[i][6])
            nmmv.append(test.iloc[i][7])

        elif i == 14: 
            i += 1    
        elif i < 19:
            ssp.append(test.iloc[i][2])
            ssv.append(test.iloc[i][5])
            nssp.append(test.iloc[i][6])
            nssv.append(test.iloc[i][7])
            
    Ap.append([name]+ap);  Av.append([name] + av)
    MSp.append([name] + msp);MSv.append([name] + msv)
    SMp.append([name] + smp);SMv.append([name] + smv)
    MMp.append([name] + mmp);MMv.append([name] + mmv)
    SSp.append([name] + ssp);SSv.append([name] + ssv)
    Np.append([name]+np);  Nv.append([name] + nv) ; Nssp.append([name] + nssp); Nmmp.append([name] + nmmp)
    Nmmv.append([name] + nmmv); Nssv.append([name] + nssv)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:56: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [34]:
df_participant5

,repas_p,temps_p,notes_p,i_p,a_p,p_p,d_p,repas_v,temps_v,notes_v,i_v,a_v,p_v,d_v,score_p,score_v,var_note_p,var_note_v
508,A2P2D1,m1,3,6,2,2,1,A4P3D4,m1,4,3,4,3,4,2,2,0,-1
508,A2P1D2,m10,3,4,2,1,2,A3P3D3,m10,3,1,3,3,3,1,2,0,1
508,A1P1D2,m2,3,3,1,1,2,A5P4D3,m2,4,6,5,4,3,2,2,-1,0
508,A2P1D1,m3,2,5,2,1,1,A4P4D4,m3,4,7,4,4,4,3,3,1,-1
508,A1P2D2,m4,3,9,1,2,2,A3P5D3,m4,3,9,3,5,3,2,3,-1,1
508,A1P1D1,m5,2,1,1,1,1,A5P3D4,m5,4,4,5,3,4,3,2,1,0
508,A2P2D2,m6,3,7,2,2,2,A4P3D3,m6,4,2,4,3,3,0,2,0,0
508,A2P2D2-2,m7,3,8,2,2,2,A4P5D4,m7,4,8,4,5,4,2,2,0,0
508,A1P2D1,m8,3,10,1,2,1,A5P5D3,m8,4,10,5,5,3,1,2,-1,0
508,A1P1D1-2,m9,2,2,1,1,1,A5P4D4,m9,4,5,5,4,4,2,2,1,0
508,A2P2D1,m1,3,6,2,2,1,A4P3D4,m1,4,3,4,3,4,3,3,0,0
508,A1P1D2,m2,3,3,1,1,2,A5P4D3,m2,4,6,5,4,3,1,2,0,-1
508,A1P2D2,m4,3,9,1,2,2,A3P5D3,m4,3,9,3,5,3,1,2,0,1
508,A2P2D2,m6,3,7,2,2,2,A4P3D3,m6,4,2,4,3,3,2,2,0,0
508,A1P2D1,m8,3,10,1,2,1,A5P5D3,m8,4,10,5,5,3,3,2,0,-1
508,A2P1D2,m10,3,4,2,1,2,A3P3D3,m10,3,1,3,3,3,1,3,-1,1
508,A2P1D1,m3,2,5,2,1,1,A4P4D4,m3,4,7,4,4,4,1,2,0,0
508,A1P1D1,m5,2,1,1,1,1,A5P3D4,m5,4,4,5,3,4,3,2,1,0
508,A2P2D2-2,m7,3,8,2,2,2,A4P5D4,m7,4,8,4,5,4,3,2,-1,0
508,A1P1D1-2,m9,2,2,1,1,1,A5P4D4,m9,4,5,5,4,4,2,2,1,0

In [35]:
df_Ap = pd.DataFrame(Ap)
df_Ap.columns = ["participant", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
df_Ap.index = df_Ap["participant"]
df_Ap = df_Ap.drop(columns = ["participant"])
df_Ap.to_csv("seris_total_peu.csv")

In [36]:
df_Av = pd.DataFrame(Av)
df_Av.columns = ["participant", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
df_Av.index = df_Av["participant"]
df_Av = df_Av.drop(columns = ["participant"])
df_Av.to_csv("seris_total_var.csv")

In [37]:
df_MSp = pd.DataFrame(MSp)
df_MSp.columns = ["participant", "1", "2", "3", "4", "5"]
df_MSp.index = df_MSp["participant"]
df_MSp = df_MSp.drop(columns = ["participant"])
df_MSp.to_csv("series_matsoi_peu.csv")

In [38]:
df_MSv = pd.DataFrame(MSv)
df_MSv.columns = ["participant", "1", "2", "3", "4", "5"]
df_MSv.index = df_MSv["participant"]
df_MSv = df_MSv.drop(columns = ["participant"])
df_MSv.to_csv("series_matsoi_var.csv")

In [39]:
df_MMp = pd.DataFrame(MMp)
df_MMp.columns = ["participant", "1", "2", "3", "4"]
df_MMp.index = df_MMp["participant"]
df_MMp = df_MMp.drop(columns = ["participant"])
df_MMp.to_csv("series_matmat_peu.csv")

In [40]:
df_MMv = pd.DataFrame(MMv)
df_MMv.columns = ["participant", "1", "2", "3", "4"]
df_MMv.index = df_MMv["participant"]
df_MMv = df_MMv.drop(columns = ["participant"])
df_MMv.to_csv("series_matmat_var.csv")

In [41]:
df_SMp = pd.DataFrame(SMp)
df_SMp.columns = ["participant", "1", "2", "3", "4"]
df_SMp.index = df_SMp["participant"]
df_SMp = df_SMp.drop(columns = ["participant"])
df_SMp.to_csv("series_soimat_peu.csv")

In [42]:
df_SMv = pd.DataFrame(SMv)
df_SMv.columns = ["participant", "1", "2", "3", "4"]
df_SMv.index = df_SMv["participant"]
df_SMv = df_SMv.drop(columns = ["participant"])
df_SMv.to_csv("series_soimat_var.csv")

In [43]:
df_SSp = pd.DataFrame(SSp)
df_SSp.columns = ["participant", "1", "2", "3", "4"]
df_SSp.index = df_SSp["participant"]
df_SSp = df_SSp.drop(columns = ["participant"])
df_SSp.to_csv("series_soisoi_peu.csv")

In [44]:
df_SSv = pd.DataFrame(SSv)
df_SSv.columns = ["participant", "1", "2", "3", "4"]
df_SSv.index = df_SSv["participant"]
df_SSv = df_SSv.drop(columns = ["participant"])
df_SSv.to_csv("series_soisoi_var.csv")

In [45]:
df_Np = pd.DataFrame(Np)
df_Np.columns = ["participant", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
df_Np.index = df_Np["participant"]
df_Np = df_Np.drop(columns = ["participant"])
df_Np.to_csv("note_total_peu.csv")

In [46]:
df_Nv = pd.DataFrame(Nv)
df_Nv.columns = ["participant", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
df_Nv.index = df_Nv["participant"]
df_Nv = df_Nv.drop(columns = ["participant"])
df_Nv.to_csv("note_total_var.csv")

In [47]:
df_Nssv = pd.DataFrame(Nssv)
df_Nssv.columns = ["participant", "1", "2", "3", "4"]
df_Nssv.index = df_Nssv["participant"]
df_Nssv = df_Nssv.drop(columns = ["participant"])
df_Nssv.to_csv("notes_soisoi_var.csv")

In [48]:
df_Nssp = pd.DataFrame(Nssp)
df_Nssp.columns = ["participant", "1", "2", "3", "4"]
df_Nssp.index = df_Nssp["participant"]
df_Nssp = df_Nssp.drop(columns = ["participant"])
df_Nssp.to_csv("notes_soisoi_peu.csv")

In [49]:
df_Nmmp = pd.DataFrame(Nmmp)
df_Nmmp.columns = ["participant", "1", "2", "3", "4"]
df_Nmmp.index = df_Nmmp["participant"]
df_Nmmp = df_Nmmp.drop(columns = ["participant"])
df_Nmmp.to_csv("notes_matmat_peu.csv")

In [50]:
df_Nmmv = pd.DataFrame(Nmmv)
df_Nmmv.columns = ["participant", "1", "2", "3", "4"]
df_Nmmv.index = df_Nmmv["participant"]
df_Nmmv = df_Nmmv.drop(columns = ["participant"])
df_Nmmv.to_csv("notes_matmat_var.csv")